name: sam2lca
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - click >=7.0
  - pip >=20.0.2
  - conda-forge::ete3 >=3.1.1
  - bioconda::pysam >=0.15.2
  - conda-forge::rocksdb >=6.10.1
  - conda-forge::python-rocksdb >=0.7.0
  - conda-forge::xopen >=0.9.0
  - tqdm>=4.45.0
  - nbsphinx
  - sphinxcontrib-napoleon
  - sphinx-click
