name: sam2lca
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=3.3.1
  - dbus=1.13.6
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - ete3=3.1.2
  - expat=2.2.10
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glib=2.66.6
  - glib-tools=2.66.6
  - icu=68.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipython_genutils=0.2.0
  - isa-l=2.30.0
  - jemalloc=5.2.1
  - jinja2=2.11.3
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - krb5=1.17.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.71.1
  - libcxx=11.0.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.66.6
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.0.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=11.0.1
  - lxml=4.6.2
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nbsphinx=0.8.1
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - nspr=4.29
  - nss=3.47
  - numpy=1.20.0
  - openssl=1.1.1i
  - packaging=20.9
  - pandas=1.2.1
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - pbr=5.5.1
  - pcre=8.44
  - pigz=2.5
  - pip=21.0.1
  - pockets=0.9.1
  - pthread-stubs=0.4
  - pycparser=2.20
  - pygments=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysam=0.16.0.1
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python-isal=0.4.0
  - python-rocksdb=0.7.0
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=22.0.1
  - qt=5.12.9
  - readline=8.0
  - requests=2.25.1
  - rocksdb=6.13.3
  - scipy=1.6.0
  - setuptools=49.6.0
  - six=1.15.0
  - snappy=1.1.8
  - snowballstemmer=2.1.0
  - sphinx=3.4.3
  - sphinx-click=2.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.34.0
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.56.0
  - traitlets=5.0.5
  - urllib3=1.26.3
  - webencodings=0.5.1
  - wheel=0.36.2
  - xopen=1.1.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8