{% set setup_data = load_setup_py_data() %}
package:
  name: sam2lca
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/maxibor/sam2lca.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - click >=7.0
    - pip >=20.0.2
    - bioconda::taxopy=0.9.2
    - bioconda::pysam >=0.15.2
    - conda-forge::rocksdb >=6.10.1
    - conda-forge::python-rocksdb >=0.7.0
    - conda-forge::xopen >=0.9.0
    - tqdm >=4.45.0
    - pandas >=1.1.4
    
test:
  imports:
    - sam2lca


about:
  home: https://github.com/maxibor/sam2lca
  license: GPL-3.0
  summary: 'Performs LCA on SAM/BAM/CRAM alignment file'

# Build using: conda build -c conda-forge .
