{% set name = "sam2lca" %}
{% set version = "1.0.0b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sam2lca-{{ version }}.tar.gz
  sha256: 6d91c363cd0aa5d13c2e3491da4241109ece3948cb038d5a621e8263cf584f60

build:
  entry_points:
    - sam2lca = sam2lca.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - pandas
    - pysam
    - python >=3.7
    - python-rocksdb
    - tqdm
    - taxopy
    - xopen

test:
  imports:
    - sam2lca
  commands:
    - pip check
    - sam2lca --help
  requires:
    - pip

about:
  home: https://github.com/maxibor/sam2lca
  summary: Last Commont Ancestor on SAM/BAM/CRAM alignment files
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxibor
