# name: pydamage_ci

# on: [push, pull_request]


# jobs:
#   pydamage_ci:
#     name: pydamage_ci
#     runs-on: 'ubuntu-latest'
#     if: "!contains(github.event.head_commit.message, '[skip_ci]')"
#     steps:
#       - uses: actions/checkout@v2
#       - uses: goanpeca/setup-miniconda@v1
#         with:
#           activate-environment: sam2lca
#           environment-file: sam2lca.yml
#           python-version: 3.7
#           auto-activate-base: false
#       - name: Lint with flake8
#         shell: bash -l {0}
#         run: |
#           pip install flake8
#           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#       - name: Test with pytest
#         shell: bash -l {0}
#         run: |
#           pip install -e .
#           pip install pytest
#           pytest
#       - name: Check pydamage help message
#         shell: bash -l {0}
#         run: |
#           sam2lca --help
#       - name: Check pydamage on test data
#         shell: bash -l {0}
#         run: |
#           pydamage --verbose tests/data/aligned.bam